### ISSUE TITLE
Moderation - the icon name does not display after the content is hidden

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#1031]
Tested on Staging iOS version 1.10.4 (7)
Tested on Staging Android version v1.0 (324)

Steps to reproduce:
1. Go to A common that you are a moderator 
2. Go to discussion 
3. Hide the discussion
4. show the discussion

Actual results:
The icon name disappear
![image](https://user-images.githubusercontent.com/69141571/149667864-c0ce6bac-bbfb-4796-bce1-b85ed66046dc.png)

https://user-images.githubusercontent.com/69141571/149667597-e55542d5-913c-4deb-b64f-c725950a0057.mp4

Expected results:
The icons name should be display

**Comment by watchtower314** [comment]
I removed the share option from common options, because we have a share button already, and removed the share from discussions/messages/proposals, as we never developed the functionality for that, it's not urgent for this release, we will deal with it on the next sprint, after we have clear specs of what needs to be done, and if we need this at all

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.10.5 (8-300)
Tested on Staging Android version v1.0 (358)
found OK
after the content is hidden only "Show" appears
