### ISSUE TITLE
Join common at the first time - instruction

### ISSUE THREAD

**Issue by HannaMaklakova** [daostack/common-backend#1146]
When user click ‘Join a common’, as long as user hasn’t joined any common yet. We should show the following screen: 
https://zpl.io/2pgeEpy
<img width="250" src="https://user-images.githubusercontent.com/87295860/154286659-e825c37b-5941-4aa9-91ba-9b62d3f1d7ce.jpeg">

**Comment by yanivi71** [comment]
@IvanSantiagoUk @watchtower314 
tested on android. seem that the screen is too big. user need to scroll in order to see the button "got it"
![Screenshot_2022-03-13-13-04-24-749_com daostack common staging](https://user-images.githubusercontent.com/69141571/158056607-d80d2d01-0b2d-4799-ae67-c56575ebcb2d.jpg)

**Comment by IvanSantiagoUk** [comment]
do you prefer to use a floating button instead?

**Comment by kazaryan-t** [comment]
Checked on iOS v1.11.2 (15-316)
Checked on Android v1.0 (401)
