### ISSUE TITLE
Force common founder to contribute to common [S10-01]

### ISSUE THREAD

**Issue by watchtower314** [daostack/common-backend#1173]
Founder of common must contribute according to the same other member demands

1. After founder review the new common they are asked to contribute according to the common definition: https://zpl.io/V1EWgBm 

2. If founder doesn’t have a credit card in the system: The founder is asked to feed Credit card:
https://zpl.io/VqQlBRN

point is in the separate [task](https://github.com/daostack/common-backend/issues/1275) 3.  If they already have a credit card in the system they confirm the payment:
https://zpl.io/VxAw4vm

4. Once payment approved - confirmation screen appears: 
https://zpl.io/agY6XPA

**Comment by yanivi71** [comment]
@watchtower314 @MeyerPV 
Tested on Staging iOS version 1.11.2 (15-316)
Tested on Staging Android version v1.0 (401)

1 The title is membership request instead of "Personal contribution" - see design
2. the rout is broken/ incorrect 
![image](https://user-images.githubusercontent.com/69141571/162918272-6c1235d4-a7e0-4332-b944-e3ff2c4f27ea.png)
3. when user has already card details - there is a missing screen
https://app.zeplin.io/project/5ef45122508c89515c9d17d8/screen/6033f34bbd2b1510de2b27ee

**Comment by MeyerPV** [comment]
@yanivi71 
Please create a separate issue for bugs. Also select the payment method was not available when completing the task and should be created as a separate feature task

**Comment by yanivi71** [comment]
@MeyerPV i open 2 issues i will test select payment method once it will be ready 
https://github.com/daostack/common-backend/issues/1273
https://github.com/daostack/common-backend/issues/1274

**Comment by yanivi71** [comment]
moved to verify
select payment method will be in a different issue
