### ISSUE TITLE
Moderation - proposal - moderator view - hidden proposal - Ui issues

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#148]
Tested on Staging iOS version 1.9.5 (4978-226)
Tested on Staging Android version 1.9.5 (4978-187)

Steps to reproduce:

1. Go to a common as moderator
2. go to proposal tab
3. click on proposal menu
4. click on hide

Actual results:
1. Background Color is wrong 
2. Status appears
see attached image

Expected results:
1. Background should be gray
2. Status should not appear

![File (54)](https://user-images.githubusercontent.com/69141571/109543378-d5938a80-7ace-11eb-90d7-b4a14df4443f.jpg)
![image](https://user-images.githubusercontent.com/69141571/109543812-72eebe80-7acf-11eb-96a7-eb5675782e95.png)

**Comment by watchtower314** [comment]
@Taikaish do we want to hide the status of the proposal when it's hidden/reported?

**Comment by Taikaish** [comment]
Good point. @watchtower314 
I think we want to hide the status, but we also need to add one more thing - 
If a proposal or a membership request is hidden by moderators, the countdown should freeze as well.
If they show it again, the countdown should start from where it stopped, or if it's less than 24 hours, the countdown should start from 24 hours. 

This is to prevent situations where the moderator hides a spam proposal but then it passes anyways because it has more upvotes than downvotes and no one can vote anymore.

What do you think?

**Comment by watchtower314** [comment]
Sounds good!

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-228)
Tested on Staging Android version 1.9.5 (4978-189)

Found OK
Background is gray
Status does not appear

**Comment by yanivi71** [comment]
verified on Production
