### ISSUE TITLE
Discussion - Ability to see new messages for a user

### ISSUE THREAD

**Issue by andreymikhadyuk** [daostack/common-backend#1613]
We need to display `new` messages for user in the chat. Maybe it worth to store last seen message id for specific user somehow?
And we also will need to display the amount of notifications in a feed item, not sure what is the better approach here, since in the future notifications amount will be not only new discussion messages amount, but also specific events that happened (which we also will display in the chat).

**Comment by ariel-dao** [comment]
I think I'll create a collection that tracks last seen for each user and each feed item, the count of new notifications per feed item is unique to a user, so it'll also be stored there.

About the last seen item, It'll be a reference to that item with the type attached, that way it'll be expandable.

![image](https://user-images.githubusercontent.com/89919079/215357473-32d8ed5d-d320-40c4-933f-00203102ce38.png)

I must add that since we are not using a messaging dedicated system, or have the optimal infrastructure (queues) this task will be considered as something that adds technical debt, working with collections for a task like this is not ideal.

**Comment by andreymikhadyuk** [comment]
@ariel-dao Will this cover new messages in the chat?

**Comment by ariel-dao** [comment]
@andreymikhadyuk What do you by new messages in the chat?

The logic will be that you will call an endpoint to mark "seen" on all messages before (an including a specific message Id you send in the body of that endpoint), this will be done by date.

If a new message appears, you need to call the endpoint for each one, or debounce the call to not spam BE if you get a surge of messages.

**Comment by ariel-dao** [comment]
@andreymikhadyuk No point to reopen this when we have https://github.com/daostack/common-backend/issues/1645
Let's stick to opening new bugs rather than reopening finished tasks
