### ISSUE TITLE
Mark as unread BE functionality

### ISSUE THREAD

**Issue by elatif2020** [daostack/common-backend#2029]
Allow marking a stream (discussion\ proposal) as unread even though all messages are read. 
Can be applied only for items in which all messages are read. So the new messages counter is initially zero but it can increase afterward. Once the user looks again in this item chat this indication is reset. 
We'll have a special indication for it in the FE. 
And also the opposite action, of marking an item as read, in this case all messages (up to this time) are marked as read and if there was mark as unread indication it is removed.

**Comment by danielr18** [comment]
@elatif2020 Should we remove the unread mark when a new message is sent? When a new message is sent, then it should just act as normal.

I noticed Slack gives the option to mark a message as unread, instead of a channel/chat, which seems more fitting to our last seen architecture. But anyways, adding this unread flag isn't complex per se.

**Comment by ariel-dao** [comment]
@elatif2020 Any update regarding @danielr18 question?

**Comment by elatif2020** [comment]
@ariel-dao thanks for reminding me 🙏 

1. Yes
2. The indication we want to show to the user is different from the usual counter, similar to Telegram's mark as unread, marking the stream as unread.
