### ISSUE TITLE
Force user to fill in his account 

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#209]
NOTE! **it's not for all the users who signed up with Apple, just those who ask apple not to share their details with us**
We need to force a user to complete his account before starting using our app 
Scenario:
1. user logged in
2. his profile was not filled (required fields)
3. we do not allow him to go to other screens before he filled in all info
4. even if he restarts the app - the complete account screen is shown again
https://zpl.io/2G8R5BY

**Comment by kazaryan-t** [comment]
Tested on Staging iOS version 1.9.5 (4978-255)

Found OK.

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.6 (4978-272)
Tested on Staging Android version 1.9.6 (4978-233)
@kazaryan-t @lpetkov-sw 

Found OK
this issue is tested through th DB. since we cannot create users in google or apple without these relevant details
1. We deleted manually the last name.
2. logged in with the user
3. details screen appears

should be verified on prod also

**Comment by yanivi71** [comment]
Verified on production
