### ISSUE TITLE
Notification screen - Rename notification for new member request

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#216]
Please, 
1. rename "You are asking to be a common member" to "Your Common has new pending members, view their requests and vote"
2. rename "membership request created" to "New members" 
3. The image for the new member notifications should be the image of the common
4. the name of the common should always display next to the time of the notification
![image](https://user-images.githubusercontent.com/28015224/110819854-a2f04b80-829f-11eb-8fe4-600efa8c56f8.png)

**Comment by yanivi71** [comment]
Tested on Staging iOS version 1.9.5 (4978-239)
Tested on Staging Android version 1.9.5 (4978-200)

@IvanSantiagoUk The fix is ok except a small issue
 
rename "You are asking to be a common member" to "Your Common has new pending members, view their requests and vote"
The word "vote " does not display instead there are 3 dots (...) - see attached image

Pass - rename "membership request created" to "New members"
Pass - The image for the new member notifications should be the image of the common
Pass  - the name of the common should always display next to the time of the notification

![image](https://user-images.githubusercontent.com/69141571/111065184-12915100-84c1-11eb-899b-840e750c010f.png)

**Comment by watchtower314** [comment]
@yanivi71 why is this issue closed? it is fixed?

**Comment by yanivi71** [comment]
Mb I closed by mistake

**Comment by watchtower314** [comment]
pr: https://github.com/daostack/common/pull/975

**Comment by kazaryan-t** [comment]
Tested on Production Android version 1.9.5 (4998-53)
Tested on Production iOS version 1.9.5 (4998-44)
