### ISSUE TITLE
PROD- a test user cant open the left navigation bar

### ISSUE THREAD

**Issue by NoamQA** [daostack/common-backend#2185]
i have a user (anothertestqa7@gmail.com)  that when i try to open the left navigation bar i get message that i dont have spaces yet
i think it could be related that i change names of circles in one of his commons (related to #[2072](https://github.com/daostack/common-web/issues/2072))

![Image](https://github.com/daostack/common-backend/assets/129174316/f996c5a7-d660-4078-ba76-d4a7754f3874)

![Image](https://github.com/daostack/common-backend/assets/129174316/829ff31e-63b9-4ad2-a206-e4058ee372bc)

**Comment by danielr18** [comment]
I've fixed the data, but not the source of the issue.

@NoamQA Can you create a list of steps to recreate this?

**Comment by NoamQA** [comment]
@danielr18 
looks like it works fine now
couldnt reproduce it...

**Comment by elatif2020** [comment]
@danielr18 
I have a similar issue in DEV with my account latif@daostack.io userId: DDLlUToombZCVE4hf6Ir0NEsOvg2

I realized that we have a mistake in the governance of related commons. For instance in [Autmun Dev](https://web-dev.common.io/commons/4c87126a-d764-42c5-90dc-723431fa5a46)  common ([this](https://console.cloud.google.com/firestore/databases/-default-/data/panel/governance/0946f300-c272-49f6-a38b-50576cc7d1b2?authuser=0&hl=en&project=common-dev-34b09) is the related governance entry in the db), the circles array contains only the hierarchical circles, but the project circles are missing.
My guess is that it is caused by the endpoint to change circles name.

**Comment by NoamQA** [comment]
@elatif2020 
can you test again in dev with your user?
it doesnt happens for me...

**Comment by NoamQA** [comment]
could be related to [#2248](https://github.com/daostack/common-web/issues/2248)
to be tested after it fixed

**Comment by elatif2020** [comment]
> could be related to [#2248](https://github.com/daostack/common-web/issues/2248) to be tested after it fixed

@NoamQA 
It's not related
