### ISSUE TITLE
Share common - Add og:type (image,title, text) to shared links

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#437]
Image = Common's cover photo

Title = name of the common.

Description = "{tagline of the common}. Download the Common app to join now."

**Comment by yanivi71** [comment]
This issue can be tested on production only

**Comment by yanivi71** [comment]
@IvanSantiagoUk @watchtower314 
Hi the share common text is incorrect.  no common name (display as undefine). no icon. no tagline. it does not equal to the design description
![image](https://user-images.githubusercontent.com/69141571/160357660-af8a8c50-83e1-4b15-b452-c18255097e2f.png)

**Comment by IvanSantiagoUk** [comment]
Fixed the undefined tagline.

This is how is sent following the documentation probably image not appearing because is not expanded but the data is there

<img width="619" alt="Screenshot 2022-05-05 at 14 08 06" src="https://user-images.githubusercontent.com/20967640/166920104-fff9ddc1-2276-4758-bbca-cd252848e0d7.png">
