### ISSUE TITLE
Update the color palette for the "avatars" of users who didn't upload a profile picture

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#485]
Please, update the color palette for the "avatars" of users who didn't upload a profile picture
https://zpl.io/a88ZRJE 
![User palette colors](https://user-images.githubusercontent.com/28015224/118474112-6152a580-b713-11eb-97af-62173c3bf7d3.png)

**Comment by IvanSantiagoUk** [comment]
Actually we are getting images with a plain color and the letter inside on the frontend on the photo_url field.

So that means than on the app we ALWAYS show an image and that photo_url is generated somewhere else. I checked on backend and it doesnt look in our side so I think is generated when we create an account and received from Google.

Nothing we can do here.
