### ISSUE TITLE
Common - add hover state for share button

### ISSUE THREAD

**Issue by gingervik** [daostack/common-backend#561]
As there is no hover state for the share button, please, add it

**Comment by yanivi71** [comment]
tested on web site
Found OK
hover state for share button is added

**Comment by Taikaish** [comment]
Fix required:

The color of the button at Hover isn't correct.
The correct color is: #5d6ef9
https://zpl.io/blOgzGk

**Comment by yanivi71** [comment]
@razoorka 
Hi now. the background color does not change when hover on shared button
my resolution is 1920X1080

**Comment by roienatan** [comment]
@Taikaish @yanivi71  Are you sure about this hover color? I ask because the share button is special among the other purple buttons (according the design it has special light purple (`#7786ff` with opacity `0.1` - almost transparent color `#f1f5ff`) and it looks bad to jump from  `#f1f5ff` to `#5d6ef9` when hovering.

**Comment by yanivi71** [comment]
Tested on web site and found OK
the background color is changes when hover on shared button
