### ISSUE TITLE
Request to join - user status is "pending after approval

### ISSUE THREAD

**Issue by yanivi71** [daostack/common-backend#828]
Steps to reproduce:
1. perform Request to join a common (verify only 1 member is in this common)
2. Fill all the relevant details
3. As a user who created the common approved the request

Actual results:
user status is "pending after approval and he is not a member. seems there is a problem with payment process
see attached image
![Image from iOS (50)](https://user-images.githubusercontent.com/69141571/138656224-4afc39c8-0ab5-4923-8856-4de3149bc3d4.png)

Expected :
user should be approved if payment is ok

**Comment by watchtower314** [comment]
@yanivi71 I got approved, and payment was processed, perhaps you have more details to help me reproduce this?
<img width="309" alt="Screen Shot 2021-10-25 at 17 03 13" src="https://user-images.githubusercontent.com/30501647/138710217-3b09993e-8fe4-4baf-88d8-8a03d8595c47.png">

**Comment by yanivi71** [comment]
@watchtower314 on my end i still see "pending payment " status. see common "once in alife time", i used visa credit card with number 4007400000000007.

**Comment by watchtower314** [comment]
@ariel-dao @SobolevYuri  @noamso1   I need your eyes on this one, basically, when a user is being approved and joined to the common, we process the payment, `createProposalPayment` calls `pollPayment` and we're trying to contact circle and get the payment approved, the issue here is that the first attempt of polling fails (and the second one that's a few hours later succeeds) so there might be something with the polling, because if I'm not mistaken, the second attempt to finalize the payment is done by a cron job `finalizePaymentCron`, what are your thoughts?

**Comment by ariel-dao** [comment]
@watchtower314 On which environment is this reproducing? @yanivi71 
And which branches?

**Comment by yanivi71** [comment]
Staging.

**Comment by ariel-dao** [comment]
@yanivi71 Does this feature exists or production? and if so, is it working with real cards?

**Comment by yanivi71** [comment]
It works. On prod but not on stg on iOS device

**Comment by ariel-dao** [comment]
@yanivi71 Is this issue specific to iOS?

**Comment by yanivi71** [comment]
Yes because on Android it was ok

**Comment by ariel-dao** [comment]
@watchtower314 if it works on Android on staging but not on iOS, I don't see a reason that the issue is related to the backend... or am I missing something?

**Comment by yanivi71** [comment]
@watchtower314 @ariel-dao
Ok. i have tested it again on staging and it works fine now
